name: Backend CI/CD

on:
  push:
    branches:
      - 11.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t kelompok11/laravel .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Set up SSH
      run: |
        # Save the private key from GitHub secrets to a file
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/ec2_key.pem
        chmod 600 ~/ec2_key.pem
        
    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/ec2_key.pem ubuntu@${{ secrets.BACKEND_IP }} << 'EOF'
        cd /home/ubuntu/laravel
        git pull
        # Install dependencies if not already installed
        if [ ! -d "vendor" ]; then
          composer install --no-interaction --prefer-dist --optimize-autoloader
        fi
        # Check if Docker is installed
        if ! command -v docker &> /dev/null; then
              echo "Docker could not be found. Please install Docker."
              exit 1
        fi
        # Stop and remove existing Docker container if exists
        sudo docker stop laravel_container || true
        sudo docker rm laravel_container || true
        # Build Docker image
        sudo docker build -t kelompok11/laravel .
        # Run the Docker container
        sudo docker run -d --name laravel_container -p 8000:8000 kelompok11/laravel
        
        # Check if the container is running and print logs if it isn't
        if [ "$(sudo docker ps -q -f name=laravel_container)" ]; then
          echo "Container is running."
        else
          echo "Container is not running. Capturing logs..."
          sudo docker logs laravel_container || true
          exit 1
        fi
        
        # Run Laravel migrations and seeds inside the running container
        sudo docker exec laravel_container php artisan migrate --force
        sudo docker exec laravel_container php artisan db:seed --force
        sudo docker exec laravel_container php artisan config:cache
        sudo docker exec laravel_container php artisan route:cache
        sudo docker exec laravel_container php artisan view:cache
        EOF
    env:
      BACKEND_IP: ${{ secrets.BACKEND_IP }}
