name: Laravel CI/CD

on:
  push:
    branches:
      - 11.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Specify your PHP version here
        extensions: mbstring, xml, curl, bcmath

    - name: Install Composer Dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Build Step
      run: echo "Building the Laravel application..."

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        # Save the private key from GitHub secrets to a file
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/ec2_key.pem
        chmod 600 ~/ec2_key.pem

    - name: Deploy Laravel to EC2
      run: |
        ssh -i ~/ec2_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.BACKEND_IP }} << EOF
          echo "Deploying Laravel application"
          
          # Update package lists
          sudo apt update
          
          # Install PHP and required extensions
          sudo apt-get install -y php php-cli php-fpm php-mysql php-mbstring php-xml php-curl php-bcmath git

          # Clone the repository if it doesn't exist
          if [ ! -d "/home/ubuntu/laravel" ]; then
            git clone https://github.com/Bogzy-Medhat/laravel.git /home/ubuntu/laravel
          fi
          
          cd /home/ubuntu/laravel
          
          # Pull the latest changes
          git pull origin master
          
          # Check if composer is installed, if not install it
          if ! [ -x "$(command -v composer)" ]; then
            curl -sS https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
          fi

          # Install Composer dependencies
          composer install --prefer-dist --no-interaction
          
          # Check if the storage and cache directories exist
          if [ -d "storage" ] && [ -d "bootstrap/cache" ]; then
            # Set file permissions (adjust according to your server configuration)
            sudo chown -R www-data:www-data storage
            sudo chown -R www-data:www-data bootstrap/cache

            # Optionally run migrations
            php artisan migrate --force
          else
            echo "Storage or cache directory does not exist."
          fi
        EOF
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        BACKEND_IP: ${{ secrets.BACKEND_IP }}
