name: Laravel CI/CD

on:
  push:
    branches:
      - 11.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t kelompok11/laravel .

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Update to PHP 8.2
        extensions: mbstring, xml, curl, bcmath

    - name: Install Composer Dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Build Step
      run: echo "Building the Laravel application..."

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        # Save the private key from GitHub secrets to a file
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/ec2_key.pem
        chmod 600 ~/ec2_key.pem

    - name: Deploy Laravel to EC2
      run: |
        ssh -i ~/ec2_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.BACKEND_IP }} << EOF
          echo "Deploying Laravel application"

          # Navigate to the Laravel directory
          cd /home/ubuntu/laravel || { echo "Directory not found"; exit 1; }

          # Pull the latest changes from the repository
          git pull

          # Stop and remove the existing Docker container if it exists
          docker stop laravel_container || true
          docker rm laravel_container || true

          # Remove the old Docker image if it exists
          docker rmi kelompok11/laravel || true

          # Build the new Docker image
          docker build -t kelompok11/laravel .

          # Run the new Docker container
          docker run -d --name laravel_container -p 8000:8000 kelompok11/laravel

          # Run Laravel migrations and seeding
          php artisan migrate --force
          php artisan db:seed --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
        EOF
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        BACKEND_IP: ${{ secrets.BACKEND_IP }}
