name: Backend CI/CD

on:
  push:
    branches:
      - 11.x

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t kelompok11/laravel .

    - name: Deploy to Backend EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.BACKEND_IP }} << EOF
        cd /home/ubuntu/laravel
        git pull
        docker stop laravel_container || true
        docker rm laravel_container || true
        docker rmi kelompok11/laravel || true
        docker build -t kelompok11/laravel .
        docker run -d --name laravel_container -p 8000:8000 kelompok11/laravel
        php artisan migrate --force
        php artisan db:seed
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        EOF